provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  buildshiprun:
    lang: go
    handler: ./buildshiprun
    image: ghcr.io/${REPO:-openfaas}/ofc-buildshiprun:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      read_timeout: 5m
      write_timeout: 5m
      write_debug: true
      read_debug: true
      scaling_factor: 50
    environment_file:
      - buildshiprun_limits.yml
      - gateway_config.yml
      - github.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret
  #      - swarm-pull-secret
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  list-functions:
    lang: go
    handler: ./list-functions
    image: ghcr.io/${REPO:-openfaas}/ofc-list-functions:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: false
      read_debug: false
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  audit-event:
    lang: go
    handler: ./audit-event
    image: ghcr.io/${REPO:-openfaas}/ofc-audit-event:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - slack.yml
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  metrics:
    lang: go
    handler: ./metrics
    image: ghcr.io/${REPO:-openfaas}/ofc-system-metrics:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - gateway_config.yml
    environment:
      content_type: "application/json"
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  function-logs:
    lang: go
    handler: ./function-logs
    image: ghcr.io/${REPO:-openfaas}/ofc-function-logs:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  echo:
    lang: go
    handler: ./echo
    image: ghcr.io/${REPO:-openfaas}/ofc-echo:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
    limits:
      memory: 64Mi
    requests:
      memory: 32Mi
      cpu: 50m
