apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus
  namespace: {{ .Values.global.coreNamespace }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app: prometheus
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          role: {{ .Values.global.functionsNamespace }}
      podSelector:
        matchLabels:
          faas_function: metrics
