name: Docker CI

on:
  push:
    branches:
    - '**'
  pull_request:
    branches: [ master ]

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      push: ${{ steps.init.outputs.push }}
      tag: ${{ steps.init.outputs.tag }}
    steps:
      - id: init
        run: |
          if [[ $GITHUB_EVENT_NAME == "push" ]]
          then
            PREFIX="refs/heads/"
            BRANCH=${GITHUB_REF#"$PREFIX"}
            if [[ $BRANCH == "master" ]]
            then
              echo "::set-output name=tag::latest"
            else
              echo "::set-output name=tag::$BRANCH"
            fi
            echo "::set-output name=push::true"
          else
            echo "::set-output name=push::false"
            echo "::set-output name=tag::pr"
          fi
  build-and-push:
    runs-on: ubuntu-latest
    needs: init
    strategy:
      matrix:
        svc: [
          edge-auth,
          edge-router
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push ${{ matrix.svc }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.svc }}
          file: ./${{ matrix.svc }}/Dockerfile
          push: ${{needs.init.outputs.push}}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.svc }}:${{needs.init.outputs.tag}}
  build-and-push-fns:
    runs-on: ubuntu-latest
    needs: init
    strategy:
      matrix:
        fn: [
          buildshiprun,
          dashboard
        ]
        include:
        - fn: dashboard
          dir: dashboard
    steps:
      - uses: actions/checkout@v2
      - name: Install faas-cli
        run: curl -sSL https://cli.openfaas.com | sh
        working-directory: ./${{ matrix.dir }}
      - name: Login to Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build function
        run: ./faas-cli build -f ./stack.yml --filter "*${{ matrix.fn }}"
        working-directory: ./${{ matrix.dir }}
      - name: Tag image
        run: |
          OLD_TAG=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep ${{ matrix.fn }})
          docker tag $OLD_TAG ${{ secrets.DOCKER_USERNAME }}/${{ matrix.fn }}:${{needs.init.outputs.tag}}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        if: needs.init.outputs.push == 'true'
      - name: Publish to Registry
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.fn }}:${{needs.init.outputs.tag}}
        if: needs.init.outputs.push == 'true'
