name: Docker CI

on:
  push:
    branches:
    - '**'
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/edge-auth
          tag_with_ref: true
          path: edge-auth
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/edge-router
          tag_with_ref: true
          path: edge-router
  build-and-push-fns:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fn: [
          buildshiprun,
          dashboard
        ]
        include:
        - fn: dashboard
          dir: dashboard
    steps:
      - uses: actions/checkout@v2
      - name: Install faas-cli
        run: curl -sSL https://cli.openfaas.com | sh
        working-directory: ./${{ matrix.dir }}
      - name: Login to Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build function
        run: ./faas-cli build -f ./stack.yml --filter "*${{ matrix.fn }}"
        working-directory: ./${{ matrix.dir }}
      - name: Tag image
        run: |
          PREFIX="refs/heads/"
          BRANCH=${GITHUB_REF#"$PREFIX"}
          if [[ $BRANCH == "master" ]]
          then
            IMAGE_TAG=latest
          else
            IMAGE_TAG=$BRANCH
          fi
          echo ::set-env name=IMAGE_TAG::$IMAGE_TAG
          OLD_TAG=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep ${{ matrix.fn }})
          docker tag $OLD_TAG ${{ secrets.DOCKER_USERNAME }}/${{ matrix.fn }}:$IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        if: github.event_name == 'push'
      - name: Publish to Registry
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.fn }}:$IMAGE_TAG
        if: github.event_name == 'push'
